源码/源码模板/test4/booktest/urls.py
from django.conf.urls import url
import views
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^(\d+)/(\d+)$',views.show,name='show'),
    url(r'^index2$', views.index2, name='index2'),
    url(r'^user1', views.user1, name='user1'),
    url(r'^user2', views.user2, name='user2'),
    url(r'^htmlTest$',views.htmlTest),
    url(r'^csrf1$',views.csrf1),
    url(r'^csrf2$',views.csrf2),
    url(r'^verifyCode$',views.verifyCode),
    url(r'^verifyTest1', views.verifyTest1),
    url(r'^verifyTest2', views.verifyTest2),

]

源码/源码模板/test4/test4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('booktest.urls',namespace='booktest'))
]

源码/源码模板/test4/booktest/models.py
from django.db import models

class BookInfo(models.Model):
    btitle=models.CharField(max_length=20)
    bpub_date=models.DateTimeField(db_column='pub_date')
    bread=models.IntegerField()
    bcommet=models.IntegerField()
    isDelete=models.BooleanField()
    class Meta():
        db_table='bookinfo'

class HeroInfo(models.Model):
    hname=models.CharField(max_length=10)
    hgender=models.BooleanField()
    hcontent=models.CharField(max_length=1000)
    isDelete=models.BooleanField()
    book=models.ForeignKey('BookInfo')
    def showname(self):
        return self.hname

源码/源码模板/test4/booktest/views.py
#coding=utf-8

from django.shortcuts import render
from django.http import HttpResponse
from models import *

def index(request):
    # hero=HeroInfo.objects.get(pk=1)
    # context={'hero':hero}

    list=HeroInfo.objects.filter(isDelete=False)
    context={'list':list}
    return render(request,'booktest/index.html',context)
def show(request,id,id2):
    context={'id':id}
    return render(request,'booktest/show.html',context)

#用于练习模板的继承
def index2(request):
    return render(request,'booktest/index2.html')
def user1(request):
    context={'uname':'习总'}
    return render(request,'booktest/user1.html',context)
def user2(request):
    return render(request,'booktest/user2.html')

#html转义
def htmlTest(request):
    context={'t1':'<h1>123</h1>'}
    return render(request,'booktest/htmlTest.html',context)

#csrf
def csrf1(request):
    return render(request,'booktest/csrf1.html')
def csrf2(request):
    uname=request.POST['uname']
    return HttpResponse(uname)

#验证码
def verifyCode(request):
    from PIL import Image,ImageDraw,ImageFont
    import random
    #创建背景色
    bgColor=(random.randrange(50,100),random.randrange(50,100),0)
    #规定宽高
    width=100
    height=25
    #创建画布
    image=Image.new('RGB',(width,height),bgColor)
    #构造字体对象
    font=ImageFont.truetype('FreeMono.ttf',24)
    #创建画笔
    draw=ImageDraw.Draw(image)
    #创建文本内容
    text='0123ABCD'
    #逐个绘制字符
    textTemp=''
    for i in range(4):
        textTemp1=text[random.randrange(0,len(text))]
        textTemp+=textTemp1
        draw.text((i*25,0),
            textTemp1,
            (255, 255, 255),
            font)
    request.session['code']=textTemp
    #保存到内存流中
    import cStringIO
    buf=cStringIO.StringIO()
    image.save(buf,'png')
    #将内存流中的内容输出到客户端
    return  HttpResponse(buf.getvalue(),'image/png')
def verifyTest1(request):
    return render(request,'booktest/verifyTest1.html')
def verifyTest2(request):
    code1=request.POST['code1']
    code2=request.session['code']
    if code1==code2:
        return HttpResponse("ok")
    else:
        return HttpResponse("no")

源码/源码模板/test4/templates/booktest/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
    {% block head %}{% endblock %}
</head>
<body>
<h1>logo</h1>
<hr>
{% block content1 %}
    <h1>abc</h1>
{% endblock %}
<hr>
<h1>contact     {{ uname }}</h1>
</body>
</html>

源码/源码模板/test4/templates/booktest/base_goods.html
{% extends 'booktest/base.html' %}

源码/源码模板/test4/templates/booktest/base_user.html
{% extends 'booktest/base.html' %}
{% block content1 %}
<table border="1">
<tr>
    <td height="300">用户<br>导航</td>
    <td>{% block user_content %}{% endblock %}</td>
</tr>
</table>
{% endblock content1 %}

源码/源码模板/test4/templates/booktest/csrf1.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
<form action="csrf2" method="post">
    {% csrf_token %}
    <input type="text" name="uname">
    <input type="submit" value="提交">
</form>
</body>
</html>

源码/源码模板/test4/templates/booktest/htmlTest.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{{ t1 }}
<hr>
{{ t1|safe }}
<hr>
{% autoescape off %}
{{ t1 }}
{% endautoescape %}
<hr>
字面值：<br>
{{ t2|default:'<h1>abc</h1>' }}
<br>
手动转义：{{ t2|default:'&lt;h1&gt;abc&lt;/h1&gt;' }}
</body>
</html>

源码/源码模板/test4/templates/booktest/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
<a href="{% url 'booktest:show' '456' '789' %}">显示</a>
<hr>
{{ hero.showname }}
<hr>
奇数行显示为红色，偶数行显示为蓝色
<hr>
{% comment %}
{#  http://blog.csdn.net/xyp84/article/details/7945094#}
{% endcomment %}
<ul>

{% for hero in list %}
    {% if forloop.counter|divisibleby:"2" %}
<li style="color:red">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% else %}
<li style="color:blue">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% endif %}
{% empty %}
    <li>啥也没找到</li>
{% endfor %}
</ul>
</body>
</html>

源码/源码模板/test4/templates/booktest/index2.html
{% extends 'booktest/base.html' %}

{% block content1 %}
<h1>123</h1>
{% endblock content1 %}

源码/源码模板/test4/templates/booktest/show.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
{{ id }}
</body>
</html>

源码/源码模板/test4/templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}
{% block head %}
<script>alert('123')</script>
{% endblock head %}
{% block user_content %}
<h1>用户中心1</h1>

{% endblock user_content %}

源码/源码模板/test4/templates/booktest/user2.html
{% extends 'booktest/base_user.html' %}
{% block user_content %}
<h1>用户中心2</h1>
{% endblock user_content %}

源码/源码模板/test4/templates/booktest/verifyTest1.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
</head>
<body>
<form action="verifyTest2" method="post">
    {% csrf_token %}
    <input type="text" name="code1">
    <img src="verifyCode">
    <input type="submit" value="提交">
</form>
</body>
</html>